<a href="https://colab.research.google.com/github/mariafernandamr/MariaFernanda-DataVisualization2023/blob/main/03_Data_Structures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is a DS?**

A DS is an object that let us store more than one value.

Formally, a DS i s a **Sequence** of values which can be located with an index.

# **2. Linear Algebra**

## 2.1. What is Numpy?

Numpy (Numerical Python) is a collection of functions and method.
Siempre hay que correr la celda siempre que se abra el archivo


In [2]:
# Install the library

import numpy as np 

# **2.2 Numpy arrays - vectors and matrices**

Vector solo tiene fila - 
Matriz tiene fila (hacia al lado) y columnas (hacia abajo)


* *Example 1 - Columna vector*



In [ ]:
a = np.array([[1],[2],[3]])
print(a)
print(a.shape)

[[1]
 [2]
 [3]]
(3, 1)


* *Example 2 - Row vector*

In [ ]:
b = np.array([[4,5,6]])
print(b)
print(b.shape)

[[4 5 6]]
(1, 3)


* *Example 3 - Matrix*

In [ ]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(M)
print(M.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
# nice trick

nr, nc = M.shape

# 2.3. Sciling 

To access one or several elements of the objects.

In [ ]:
# Extract the first element 

## Column vector
print(a[0,0])

## Row vector
print(b[0,0])

## Matrix
print(M[0,0])

1
4
1


In [ ]:
# Extract the last element

## Column vector
print(a[-1,0])

## Row vector
print(b[0,-1])

## Matrix
print(M[-1,-1])

3
6
9


In [ ]:
# Extract a subset

## Column vector
print(a[0:2])

## Row vector
print(b[0,0:2])

## Matrix
print(M[0:2,0:2])

[[1]
 [2]]
[4 5]
[[1 2]
 [4 5]]


# 2.4. Methods

In [ ]:
# ZEROS
z1 = np.zeros(4)
print(z1)

z2 = np.zeros((3,2))
print(z2)

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
#ONES
o1 = np.ones(4)
print(o1)

o2 = np.ones((3,2))
print(o2)

o2*5

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[5., 5.],
       [5., 5.],
       [5., 5.]])

**ANOTHER CREATION OPTIONS**


In [ ]:
# Full
Se usa para crear matriz con un mismo numero (solo se debe cambiar el numero final)

f = np.full((3,2),3.186)
print(f)

[[3.186 3.186]
 [3.186 3.186]
 [3.186 3.186]]


In [ ]:
# Linear sequence 

np.arange(6)

#Si se quiere que empiee en 23 y termine en 32
np.arange(23,33)

#Se incrementa por el valor que uno ponga, en este caso 0.5 (step)
np.arange(23,33,0.5) 

array([23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. ,
       28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5])

In [ ]:
# Linear space 
# Dividir en partes iguales
#Quiero que empiece en 15  termine en 90 y se divida en 6 partes iguales

np.linspace(15,90,6)

array([15., 30., 45., 60., 75., 90.])

## 2.5. Random Numbers



### Uniform distibution in the interval [0,1)

In [ ]:
# A Single Value

#Same number
np.random.seed(1234)

#A single value - between 0 and 1
np.random.rand()

0.1915194503788923

In [ ]:
# Example - Toss a coin

if np.random.rand() < 0.5 :
  print('head') 
else:
  print('tails')

tails


In [ ]:
# Two heads in a row

if np.random.rand() < 0.25 :
  print('You win!') 
else:
  print('You lose!')

You lose!


In [ ]:
# Two heads in a row

#Primer lanzamiento
ft = np.random.rand()
if ft < 0.5 :
  print('The first toss was head') 
else:
  print('The first toss was tails')

#Segundo lanzamiento
st = np.random.rand()
if st < 0.5 :
  print('The second toss was head') 
else:
  print('The second toss was tails')

#Si el primer lanzamiento es igual al segundo ganas, si no pierdes
if ft < 0.5 and st < 0.5:
  print('You win!')
else:
  print('You lose!')

The first toss was head
The second toss was head
You win!


In [3]:
#One dimensional array
#Cantidad de numeros aleatorios (en este caso 5 numeros aleatorios entre 0 y 1)
np.random.rand(5)

array([0.69180865, 0.62737885, 0.37485132, 0.49589886, 0.89668444])

In [4]:
#Matrix
#El primero numero que se pone son las filas 
np.random.rand(6,2)

array([[0.67125151, 0.2840867 ],
       [0.95596937, 0.83255601],
       [0.41735534, 0.34356213],
       [0.673656  , 0.68131974],
       [0.49789248, 0.84431105],
       [0.69544132, 0.74872951]])

### Uniform distibution in the interval [a,b)

In [8]:
# Single value
#Numero aleatorio entre -10 y 0
np.random.uniform(low = -10, high = 0)

-2.227812711243553

In [9]:
#One dimensional array
#Numero aleatorio entre -10 y 0 (solo 7 numeros)
np.random.uniform(low = -10, high = 0, size = 7 )

array([-3.05217776, -9.45955809, -1.56071925, -2.17164825, -7.13135464,
       -7.01506022, -1.04377108])

In [10]:
#Matix
#Numero aleatorio entre -10 y 0 (5 es el numero de la fila - se debe poner primero) , (1 columna)
np.random.uniform(low = -10, high = 0, size = (5,1))

array([[-2.50597567],
       [-8.73292515],
       [-4.10932542],
       [-9.35337398],
       [-4.1755542 ]])

**Exercise**
Simulate the sale of a shop according to 

| Scenario | Prob | Sales |
|----------|------|-------|
|Bad       | 25%  |  60   |
|Normal    | 50%  |  80   |
|Wow       | 25%  |  100  |

For 5 days.

In [43]:
#A Solution 
#Ejercicio se basa en prediciones de ventas para 5 dias 

for i in range(1,6):
  tmp = np.random.rand()
  if tmp <0.25:
    print('Day',i, 'Scenario: Bad -','Units sold:60')
  elif tmp>0.75:
    print('Day',i,'Scenario: Wow - ','Units sold:100')
  else:
    print('Day',i,'Scenario: Normal - ','Units sold:80')

Day 1 Scenario: Wow -  Units sold:100
Day 2 Scenario: Bad - Units sold:60
Day 3 Scenario: Bad - Units sold:60
Day 4 Scenario: Bad - Units sold:60
Day 5 Scenario: Normal -  Units sold:80
